/**
 * Auto-generated database TypeScript types.
 * This file will be regenerated by: supabase gen types typescript --local
 * 
 * For now, this is hand-crafted based on the schema in docs/plan/05-database-schema.md
 * and will be replaced once the Supabase CLI is configured locally.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// --- Enum string literal types (mirror PostgreSQL enums) ---
export type UserRole = "admin" | "requester" | "focal_point" | "staff" | "compliance";
export type UserStatus = "pending" | "active" | "rejected" | "inactive";
export type ItemCategory = "chemical_reagent" | "calibration_std" | "gas" | "material_supply" | "peroxide";
export type OrderStatus = "pending" | "approved" | "rejected" | "ordered" | "partially_received" | "received" | "closed";
export type LotStatus = "active" | "depleted" | "expired" | "quarantined" | "disposed";
export type InspectionStatus = "normal" | "warning" | "quarantine";
export type ExtensionStatus = "pending" | "approved" | "rejected";
export type RegulatoryStatus = "active" | "expired" | "pending_review";
export type TransactionType =
  | "order_created"
  | "order_approved"
  | "order_rejected"
  | "check_in"
  | "check_out"
  | "inspection"
  | "shelf_life_extension"
  | "regulatory_update"
  | "user_approved";

// --- Row types per table ---

export interface Database {
  public: {
    Tables: {
      villages: {
        Row: {
          id: string;
          name: string;
          code: string;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["villages"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["villages"]["Insert"]>;
      };
      labs: {
        Row: {
          id: string;
          village_id: string;
          name: string;
          code: string;
          location: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["labs"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["labs"]["Insert"]>;
      };
      user_profiles: {
        Row: {
          id: string;
          auth_user_id: string;
          full_name: string;
          email: string;
          role: UserRole | null;
          village_id: string | null;
          lab_id: string | null;
          status: UserStatus;
          approved_by: string | null;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["user_profiles"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["user_profiles"]["Insert"]>;
      };
      item_master: {
        Row: {
          id: string;
          name: string;
          cas_number: string | null;
          category: ItemCategory;
          unit: string;
          is_peroxide: boolean;
          is_regulated: boolean;
          min_stock_level: number | null;
          storage_requirements: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["item_master"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["item_master"]["Insert"]>;
      };
      purchase_orders: {
        Row: {
          id: string;
          po_number: string | null;
          item_id: string;
          village_id: string;
          lab_id: string;
          quantity: number;
          unit: string;
          purpose: string | null;
          requester_id: string;
          status: OrderStatus;
          approved_by: string | null;
          approved_at: string | null;
          reject_reason: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["purchase_orders"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["purchase_orders"]["Insert"]>;
      };
      item_lots: {
        Row: {
          id: string;
          purchase_order_id: string;
          item_id: string;
          village_id: string;
          lab_id: string;
          lot_number: string;
          received_quantity: number;
          remaining_quantity: number;
          unit: string;
          manufacture_date: string | null;
          expiry_date: string | null;
          received_date: string;
          received_by: string;
          supplier: string | null;
          is_peroxide: boolean;
          status: LotStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["item_lots"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["item_lots"]["Insert"]>;
      };
      checkouts: {
        Row: {
          id: string;
          lot_id: string;
          quantity: number;
          purpose: string | null;
          checked_out_by: string;
          checked_out_at: string;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["checkouts"]["Row"], "id" | "created_at">;
        Update: never;
      };
      peroxide_inspections: {
        Row: {
          id: string;
          lot_id: string;
          inspection_date: string;
          ppm_reading: number;
          status: InspectionStatus;
          inspector_id: string;
          notes: string | null;
          action_taken: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["peroxide_inspections"]["Row"], "id" | "created_at">;
        Update: never;
      };
      shelf_life_extensions: {
        Row: {
          id: string;
          lot_id: string;
          old_expiry_date: string;
          new_expiry_date: string;
          reason: string;
          requested_by: string;
          approved_by: string | null;
          status: ExtensionStatus;
          review_date: string | null;
          reject_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["shelf_life_extensions"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["shelf_life_extensions"]["Insert"]>;
      };
      regulatory_records: {
        Row: {
          id: string;
          item_id: string;
          regulation_type: string;
          regulation_code: string | null;
          status: RegulatoryStatus;
          effective_date: string | null;
          expiry_date: string | null;
          description: string | null;
          is_controlled: boolean;
          village_id: string | null;
          lab_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["regulatory_records"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["regulatory_records"]["Insert"]>;
      };
      regulatory_record_lots: {
        Row: {
          id: string;
          regulatory_record_id: string;
          lot_id: string;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["regulatory_record_lots"]["Row"], "id" | "created_at">;
        Update: never;
      };
      transactions: {
        Row: {
          id: string;
          type: TransactionType;
          reference_id: string;
          reference_type: string;
          description: string;
          user_id: string;
          village_id: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["transactions"]["Row"], "id" | "created_at">;
        Update: never;
      };
      system_settings: {
        Row: {
          id: string;
          key: string;
          value: Json;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["system_settings"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["system_settings"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: {
      generate_po_number: {
        Args: { village_code: string; year: number };
        Returns: string;
      };
      perform_checkout: {
        Args: {
          p_lot_id: string;
          p_quantity: number;
          p_user_id: string;
          p_purpose: string | null;
        };
        Returns: string;
      };
    };
    Enums: {
      user_role: UserRole;
      user_status: UserStatus;
      item_category: ItemCategory;
      order_status: OrderStatus;
      lot_status: LotStatus;
      inspection_status: InspectionStatus;
      extension_status: ExtensionStatus;
      regulatory_status: RegulatoryStatus;
      transaction_type: TransactionType;
    };
  };
}
